server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:public;MODE=MYSQL;DATABASE_TO_UPPER=false;INIT=CREATE SCHEMA IF NOT EXISTS public
    username: sa
    password:
    schema:
      - classpath:sql/admin_20200623.sql
    sql-script-encoding: utf-8
    platform: h2
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2/console
      settings:
        web-allow-others: true